apiVersion: v1
kind: Service
metadata:
  name: cart-storefront-integration-api-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: cart-storefront-integration-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  sessionAffinity: None
